export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS = 'GET_USERS';
export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST';
export const REMOVE_USER = 'REMOVE_USER';
export const USERS_REQUEST_FAILED = 'USERS_REQUEST_FAILED';

export const GET_USER = 'GET_USER';
export const USER_UPDATE_GROUPS = 'USER_UPDATE_GROUPS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST';
export const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
export const SEARCH_GROUPS_REQUEST = 'SEARCH_GROUPS_REQUEST';
export const REMOVE_GROUP = 'REMOVE_GROUP';
export const REMOVE_GROUP_REQUEST = 'REMOVE_GROUP_REQUEST';
export const GROUPS_REQUEST_FAILED = 'GROUPS_REQUEST_FAILED';

export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GROUP_UPDATE_USERS = 'GROUP_UPDATE_USERS';
export const REMOVE_USER_FROM_GROUP = 'REMOVE_USER_FROM_GROUP';
export const GROUP_REQUEST_FAILED = 'GROUP_REQUEST_FAILED';
export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';