export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS = 'GET_USERS';
export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST';
export const REMOVE_USER = 'REMOVE_USER';
export const USERS_REQUEST_FAILED = 'USERS_REQUEST_FAILED';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
export const SEARCH_GROUPS_REQUEST = 'SEARCH_GROUPS_REQUEST';
export const REMOVE_GROUP = 'REMOVE_GROUP';
export const REMOVE_GROUP_REQUEST = 'REMOVE_GROUP_REQUEST';
export const GROUPS_REQUEST_FAILED = 'GROUPS_REQUEST_FAILED';