export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const REMOVE_USER_PENDING = 'REMOVE_USER_PENDING';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAIL = 'REMOVE_USER_FAIL';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const USER_LEAVE_GROUP_SUCCESS = 'USER_LEAVE_GROUP_SUCCESS';
export const USER_LEAVE_GROUP_FAIL = 'USER_LEAVE_GROUP_FAIL';
export const USER_JOIN_GROUP_SUCCESS = 'USER_JOIN_GROUP_SUCCESS';
export const USER_JOIN_GROUP_FAIL = 'USER_JOIN_GROUP_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const USER_LEAVE_GROUP_PENDING = 'USER_LEAVE_GROUP_PENDING';
export const USER_JOIN_GROUP_PENDING = 'USER_JOIN_GROUP_PENDING';

export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_PENDING = 'GET_GROUPS_PENDING';
export const REMOVE_GROUP_SUCCESS = 'REMOVE_GROUP_SUCCESS';
export const REMOVE_GROUP_PENDING = 'REMOVE_GROUP_PENDING';
export const REMOVE_GROUP_FAIL = 'REMOVE_GROUP_FAIL';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';

export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_PENDING = 'GET_GROUP_PENDING';
export const GET_GROUP_FAIL = 'GET_GROUP_FAIL';
export const REMOVE_USER_FROM_GROUP_PENDING = 'REMOVE_USER_FROM_GROUP_PENDING';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_PENDING = 'UPDATE_GROUP_PENDING';
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL';

export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_CREATE_PENDING = 'USER_CREATE_PENDING';
export const GROUP_CREATED_SUCCESS = 'GROUP_CREATED_SUCCESS';
export const GROUP_CREATE_PENDING = 'GROUP_CREATE_PENDING';
export const CREATE_USER_FAIL = 'CREATE_REQUEST_FAILED';
export const CREATE_GROUP_FAIL = 'CREATE_REQUEST_FAILED';

export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAILED';

export const IS_USER_WANT_JOIN_GROUP = 'IS_USER_WANT_JOIN_GROUP';